/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BriefUserDTO } from './BriefUserDTO';
import {
    BriefUserDTOFromJSON,
    BriefUserDTOFromJSONTyped,
    BriefUserDTOToJSON,
} from './BriefUserDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BriefUserDTORequestResponse
 */
export interface BriefUserDTORequestResponse {
    /**
     * 
     * @type {BriefUserDTO}
     * @memberof BriefUserDTORequestResponse
     */
    response?: BriefUserDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BriefUserDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the BriefUserDTORequestResponse interface.
 */
export function instanceOfBriefUserDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BriefUserDTORequestResponseFromJSON(json: any): BriefUserDTORequestResponse {
    return BriefUserDTORequestResponseFromJSONTyped(json, false);
}

export function BriefUserDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BriefUserDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : BriefUserDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BriefUserDTORequestResponseToJSON(value?: BriefUserDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': BriefUserDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

