/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BriefTeddyItemDTO } from './BriefTeddyItemDTO';
import {
    BriefTeddyItemDTOFromJSON,
    BriefTeddyItemDTOFromJSONTyped,
    BriefTeddyItemDTOToJSON,
} from './BriefTeddyItemDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BriefTeddyItemDTORequestResponse
 */
export interface BriefTeddyItemDTORequestResponse {
    /**
     * 
     * @type {BriefTeddyItemDTO}
     * @memberof BriefTeddyItemDTORequestResponse
     */
    response?: BriefTeddyItemDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BriefTeddyItemDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the BriefTeddyItemDTORequestResponse interface.
 */
export function instanceOfBriefTeddyItemDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BriefTeddyItemDTORequestResponseFromJSON(json: any): BriefTeddyItemDTORequestResponse {
    return BriefTeddyItemDTORequestResponseFromJSONTyped(json, false);
}

export function BriefTeddyItemDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BriefTeddyItemDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : BriefTeddyItemDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BriefTeddyItemDTORequestResponseToJSON(value?: BriefTeddyItemDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': BriefTeddyItemDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

