/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BriefTeddyItemDTOPagedResponse } from './BriefTeddyItemDTOPagedResponse';
import {
    BriefTeddyItemDTOPagedResponseFromJSON,
    BriefTeddyItemDTOPagedResponseFromJSONTyped,
    BriefTeddyItemDTOPagedResponseToJSON,
} from './BriefTeddyItemDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BriefTeddyItemDTOPagedResponseRequestResponse
 */
export interface BriefTeddyItemDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {BriefTeddyItemDTOPagedResponse}
     * @memberof BriefTeddyItemDTOPagedResponseRequestResponse
     */
    response?: BriefTeddyItemDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BriefTeddyItemDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the BriefTeddyItemDTOPagedResponseRequestResponse interface.
 */
export function instanceOfBriefTeddyItemDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BriefTeddyItemDTOPagedResponseRequestResponseFromJSON(json: any): BriefTeddyItemDTOPagedResponseRequestResponse {
    return BriefTeddyItemDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function BriefTeddyItemDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BriefTeddyItemDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : BriefTeddyItemDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BriefTeddyItemDTOPagedResponseRequestResponseToJSON(value?: BriefTeddyItemDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': BriefTeddyItemDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

