/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BriefTeddyItemDTO } from './BriefTeddyItemDTO';
import {
    BriefTeddyItemDTOFromJSON,
    BriefTeddyItemDTOFromJSONTyped,
    BriefTeddyItemDTOToJSON,
} from './BriefTeddyItemDTO';

/**
 * 
 * @export
 * @interface BriefTeddyItemDTOPagedResponse
 */
export interface BriefTeddyItemDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof BriefTeddyItemDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof BriefTeddyItemDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BriefTeddyItemDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<BriefTeddyItemDTO>}
     * @memberof BriefTeddyItemDTOPagedResponse
     */
    data?: Array<BriefTeddyItemDTO> | null;
}

/**
 * Check if a given object implements the BriefTeddyItemDTOPagedResponse interface.
 */
export function instanceOfBriefTeddyItemDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BriefTeddyItemDTOPagedResponseFromJSON(json: any): BriefTeddyItemDTOPagedResponse {
    return BriefTeddyItemDTOPagedResponseFromJSONTyped(json, false);
}

export function BriefTeddyItemDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BriefTeddyItemDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(BriefTeddyItemDTOFromJSON)),
    };
}

export function BriefTeddyItemDTOPagedResponseToJSON(value?: BriefTeddyItemDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(BriefTeddyItemDTOToJSON)),
    };
}

