/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TeddyItemCategoryEnum } from './TeddyItemCategoryEnum';
import {
    TeddyItemCategoryEnumFromJSON,
    TeddyItemCategoryEnumFromJSONTyped,
    TeddyItemCategoryEnumToJSON,
} from './TeddyItemCategoryEnum';
import type { TeddyItemValability } from './TeddyItemValability';
import {
    TeddyItemValabilityFromJSON,
    TeddyItemValabilityFromJSONTyped,
    TeddyItemValabilityToJSON,
} from './TeddyItemValability';

/**
 * 
 * @export
 * @interface BriefTeddyItemDTO
 */
export interface BriefTeddyItemDTO {
    /**
     * 
     * @type {string}
     * @memberof BriefTeddyItemDTO
     */
    sku?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BriefTeddyItemDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BriefTeddyItemDTO
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof BriefTeddyItemDTO
     */
    description?: string | null;
    /**
     * 
     * @type {TeddyItemCategoryEnum}
     * @memberof BriefTeddyItemDTO
     */
    category?: TeddyItemCategoryEnum;
    /**
     * 
     * @type {TeddyItemValability}
     * @memberof BriefTeddyItemDTO
     */
    valability?: TeddyItemValability;
}

/**
 * Check if a given object implements the BriefTeddyItemDTO interface.
 */
export function instanceOfBriefTeddyItemDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BriefTeddyItemDTOFromJSON(json: any): BriefTeddyItemDTO {
    return BriefTeddyItemDTOFromJSONTyped(json, false);
}

export function BriefTeddyItemDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BriefTeddyItemDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sku': !exists(json, 'sku') ? undefined : json['sku'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'category': !exists(json, 'category') ? undefined : TeddyItemCategoryEnumFromJSON(json['category']),
        'valability': !exists(json, 'valability') ? undefined : TeddyItemValabilityFromJSON(json['valability']),
    };
}

export function BriefTeddyItemDTOToJSON(value?: BriefTeddyItemDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sku': value.sku,
        'name': value.name,
        'price': value.price,
        'description': value.description,
        'category': TeddyItemCategoryEnumToJSON(value.category),
        'valability': TeddyItemValabilityToJSON(value.valability),
    };
}

