/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface GuidICollectionRequestResponse
 */
export interface GuidICollectionRequestResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof GuidICollectionRequestResponse
     */
    readonly response?: Array<string> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof GuidICollectionRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the GuidICollectionRequestResponse interface.
 */
export function instanceOfGuidICollectionRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GuidICollectionRequestResponseFromJSON(json: any): GuidICollectionRequestResponse {
    return GuidICollectionRequestResponseFromJSONTyped(json, false);
}

export function GuidICollectionRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidICollectionRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : json['response'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function GuidICollectionRequestResponseToJSON(value?: GuidICollectionRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

