/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { OrderViewDTO } from './OrderViewDTO';
import {
    OrderViewDTOFromJSON,
    OrderViewDTOFromJSONTyped,
    OrderViewDTOToJSON,
} from './OrderViewDTO';

/**
 * 
 * @export
 * @interface OrderViewDTORequestResponse
 */
export interface OrderViewDTORequestResponse {
    /**
     * 
     * @type {OrderViewDTO}
     * @memberof OrderViewDTORequestResponse
     */
    response?: OrderViewDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof OrderViewDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the OrderViewDTORequestResponse interface.
 */
export function instanceOfOrderViewDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderViewDTORequestResponseFromJSON(json: any): OrderViewDTORequestResponse {
    return OrderViewDTORequestResponseFromJSONTyped(json, false);
}

export function OrderViewDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderViewDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : OrderViewDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function OrderViewDTORequestResponseToJSON(value?: OrderViewDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': OrderViewDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

