/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TeddyBuildDTO } from './TeddyBuildDTO';
import {
    TeddyBuildDTOFromJSON,
    TeddyBuildDTOFromJSONTyped,
    TeddyBuildDTOToJSON,
} from './TeddyBuildDTO';

/**
 * 
 * @export
 * @interface TeddyBuildDTORequestResponse
 */
export interface TeddyBuildDTORequestResponse {
    /**
     * 
     * @type {TeddyBuildDTO}
     * @memberof TeddyBuildDTORequestResponse
     */
    response?: TeddyBuildDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TeddyBuildDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TeddyBuildDTORequestResponse interface.
 */
export function instanceOfTeddyBuildDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyBuildDTORequestResponseFromJSON(json: any): TeddyBuildDTORequestResponse {
    return TeddyBuildDTORequestResponseFromJSONTyped(json, false);
}

export function TeddyBuildDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyBuildDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : TeddyBuildDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TeddyBuildDTORequestResponseToJSON(value?: TeddyBuildDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': TeddyBuildDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

