/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TeddyItemDTO } from './TeddyItemDTO';
import {
    TeddyItemDTOFromJSON,
    TeddyItemDTOFromJSONTyped,
    TeddyItemDTOToJSON,
} from './TeddyItemDTO';

/**
 * 
 * @export
 * @interface TeddyItemDTORequestResponse
 */
export interface TeddyItemDTORequestResponse {
    /**
     * 
     * @type {TeddyItemDTO}
     * @memberof TeddyItemDTORequestResponse
     */
    response?: TeddyItemDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TeddyItemDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TeddyItemDTORequestResponse interface.
 */
export function instanceOfTeddyItemDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyItemDTORequestResponseFromJSON(json: any): TeddyItemDTORequestResponse {
    return TeddyItemDTORequestResponseFromJSONTyped(json, false);
}

export function TeddyItemDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyItemDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : TeddyItemDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TeddyItemDTORequestResponseToJSON(value?: TeddyItemDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': TeddyItemDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

