/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeddySkuDTO
 */
export interface TeddySkuDTO {
    /**
     * 
     * @type {string}
     * @memberof TeddySkuDTO
     */
    sku?: string | null;
}

/**
 * Check if a given object implements the TeddySkuDTO interface.
 */
export function instanceOfTeddySkuDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddySkuDTOFromJSON(json: any): TeddySkuDTO {
    return TeddySkuDTOFromJSONTyped(json, false);
}

export function TeddySkuDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddySkuDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sku': !exists(json, 'sku') ? undefined : json['sku'],
    };
}

export function TeddySkuDTOToJSON(value?: TeddySkuDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sku': value.sku,
    };
}

