/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TeddyBuildDTO } from './TeddyBuildDTO';
import {
    TeddyBuildDTOFromJSON,
    TeddyBuildDTOFromJSONTyped,
    TeddyBuildDTOToJSON,
} from './TeddyBuildDTO';

/**
 * 
 * @export
 * @interface TeddyBuildDTOPagedResponse
 */
export interface TeddyBuildDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof TeddyBuildDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof TeddyBuildDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TeddyBuildDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<TeddyBuildDTO>}
     * @memberof TeddyBuildDTOPagedResponse
     */
    data?: Array<TeddyBuildDTO> | null;
}

/**
 * Check if a given object implements the TeddyBuildDTOPagedResponse interface.
 */
export function instanceOfTeddyBuildDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyBuildDTOPagedResponseFromJSON(json: any): TeddyBuildDTOPagedResponse {
    return TeddyBuildDTOPagedResponseFromJSONTyped(json, false);
}

export function TeddyBuildDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyBuildDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(TeddyBuildDTOFromJSON)),
    };
}

export function TeddyBuildDTOPagedResponseToJSON(value?: TeddyBuildDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(TeddyBuildDTOToJSON)),
    };
}

