/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TeddyTemplateViewDTO } from './TeddyTemplateViewDTO';
import {
    TeddyTemplateViewDTOFromJSON,
    TeddyTemplateViewDTOFromJSONTyped,
    TeddyTemplateViewDTOToJSON,
} from './TeddyTemplateViewDTO';

/**
 * 
 * @export
 * @interface TeddyTemplateViewDTOPagedResponse
 */
export interface TeddyTemplateViewDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof TeddyTemplateViewDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof TeddyTemplateViewDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TeddyTemplateViewDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<TeddyTemplateViewDTO>}
     * @memberof TeddyTemplateViewDTOPagedResponse
     */
    data?: Array<TeddyTemplateViewDTO> | null;
}

/**
 * Check if a given object implements the TeddyTemplateViewDTOPagedResponse interface.
 */
export function instanceOfTeddyTemplateViewDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyTemplateViewDTOPagedResponseFromJSON(json: any): TeddyTemplateViewDTOPagedResponse {
    return TeddyTemplateViewDTOPagedResponseFromJSONTyped(json, false);
}

export function TeddyTemplateViewDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyTemplateViewDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(TeddyTemplateViewDTOFromJSON)),
    };
}

export function TeddyTemplateViewDTOPagedResponseToJSON(value?: TeddyTemplateViewDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(TeddyTemplateViewDTOToJSON)),
    };
}

