/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { VendorBriefViewPagedResponse } from './VendorBriefViewPagedResponse';
import {
    VendorBriefViewPagedResponseFromJSON,
    VendorBriefViewPagedResponseFromJSONTyped,
    VendorBriefViewPagedResponseToJSON,
} from './VendorBriefViewPagedResponse';

/**
 * 
 * @export
 * @interface VendorBriefViewPagedResponseRequestResponse
 */
export interface VendorBriefViewPagedResponseRequestResponse {
    /**
     * 
     * @type {VendorBriefViewPagedResponse}
     * @memberof VendorBriefViewPagedResponseRequestResponse
     */
    response?: VendorBriefViewPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof VendorBriefViewPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the VendorBriefViewPagedResponseRequestResponse interface.
 */
export function instanceOfVendorBriefViewPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VendorBriefViewPagedResponseRequestResponseFromJSON(json: any): VendorBriefViewPagedResponseRequestResponse {
    return VendorBriefViewPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function VendorBriefViewPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorBriefViewPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : VendorBriefViewPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function VendorBriefViewPagedResponseRequestResponseToJSON(value?: VendorBriefViewPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': VendorBriefViewPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

