/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
} from './PaymentMethod';
import type { VendorContractRenewalTerms } from './VendorContractRenewalTerms';
import {
    VendorContractRenewalTermsFromJSON,
    VendorContractRenewalTermsFromJSONTyped,
    VendorContractRenewalTermsToJSON,
} from './VendorContractRenewalTerms';

/**
 * 
 * @export
 * @interface VendorAddDTO
 */
export interface VendorAddDTO {
    /**
     * 
     * @type {string}
     * @memberof VendorAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorAddDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorAddDTO
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorAddDTO
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof VendorAddDTO
     */
    contractStartDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof VendorAddDTO
     */
    contractEndDate?: Date;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof VendorAddDTO
     */
    paymentMethod?: PaymentMethod;
    /**
     * 
     * @type {VendorContractRenewalTerms}
     * @memberof VendorAddDTO
     */
    contractRenewalTerms?: VendorContractRenewalTerms;
}

/**
 * Check if a given object implements the VendorAddDTO interface.
 */
export function instanceOfVendorAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VendorAddDTOFromJSON(json: any): VendorAddDTO {
    return VendorAddDTOFromJSONTyped(json, false);
}

export function VendorAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'contractStartDate': !exists(json, 'contractStartDate') ? undefined : (new Date(json['contractStartDate'])),
        'contractEndDate': !exists(json, 'contractEndDate') ? undefined : (new Date(json['contractEndDate'])),
        'paymentMethod': !exists(json, 'paymentMethod') ? undefined : PaymentMethodFromJSON(json['paymentMethod']),
        'contractRenewalTerms': !exists(json, 'contractRenewalTerms') ? undefined : VendorContractRenewalTermsFromJSON(json['contractRenewalTerms']),
    };
}

export function VendorAddDTOToJSON(value?: VendorAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'address': value.address,
        'phoneNumber': value.phoneNumber,
        'contractStartDate': value.contractStartDate === undefined ? undefined : (value.contractStartDate.toISOString().substr(0,10)),
        'contractEndDate': value.contractEndDate === undefined ? undefined : (value.contractEndDate.toISOString().substr(0,10)),
        'paymentMethod': PaymentMethodToJSON(value.paymentMethod),
        'contractRenewalTerms': VendorContractRenewalTermsToJSON(value.contractRenewalTerms),
    };
}

