/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VendorBriefView
 */
export interface VendorBriefView {
    /**
     * 
     * @type {string}
     * @memberof VendorBriefView
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorBriefView
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorBriefView
     */
    address?: string | null;
}

/**
 * Check if a given object implements the VendorBriefView interface.
 */
export function instanceOfVendorBriefView(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VendorBriefViewFromJSON(json: any): VendorBriefView {
    return VendorBriefViewFromJSONTyped(json, false);
}

export function VendorBriefViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorBriefView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function VendorBriefViewToJSON(value?: VendorBriefView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'address': value.address,
    };
}

