/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FeedbackServiceAction = {
    BuyTeddy: 'BuyTeddy',
    ReturnTeddy: 'ReturnTeddy',
    ShippingTeddy: 'ShippingTeddy',
    Cashback: 'Cashback'
} as const;
export type FeedbackServiceAction = typeof FeedbackServiceAction[keyof typeof FeedbackServiceAction];


export function FeedbackServiceActionFromJSON(json: any): FeedbackServiceAction {
    return FeedbackServiceActionFromJSONTyped(json, false);
}

export function FeedbackServiceActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackServiceAction {
    return json as FeedbackServiceAction;
}

export function FeedbackServiceActionToJSON(value?: FeedbackServiceAction | null): any {
    return value as any;
}

