/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FeedbackGrade = {
    Poor: 'Poor',
    Average: 'Average',
    Good: 'Good',
    Excellent: 'Excellent',
    VeryPoor: 'VeryPoor'
} as const;
export type FeedbackGrade = typeof FeedbackGrade[keyof typeof FeedbackGrade];


export function FeedbackGradeFromJSON(json: any): FeedbackGrade {
    return FeedbackGradeFromJSONTyped(json, false);
}

export function FeedbackGradeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackGrade {
    return json as FeedbackGrade;
}

export function FeedbackGradeToJSON(value?: FeedbackGrade | null): any {
    return value as any;
}

