/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { GuidPagedResponse } from './GuidPagedResponse';
import {
    GuidPagedResponseFromJSON,
    GuidPagedResponseFromJSONTyped,
    GuidPagedResponseToJSON,
} from './GuidPagedResponse';

/**
 * 
 * @export
 * @interface GuidPagedResponseRequestResponse
 */
export interface GuidPagedResponseRequestResponse {
    /**
     * 
     * @type {GuidPagedResponse}
     * @memberof GuidPagedResponseRequestResponse
     */
    response?: GuidPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof GuidPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the GuidPagedResponseRequestResponse interface.
 */
export function instanceOfGuidPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GuidPagedResponseRequestResponseFromJSON(json: any): GuidPagedResponseRequestResponse {
    return GuidPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function GuidPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : GuidPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function GuidPagedResponseRequestResponseToJSON(value?: GuidPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': GuidPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

