/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuidPagedResponse
 */
export interface GuidPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof GuidPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof GuidPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof GuidPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GuidPagedResponse
     */
    data?: Array<string> | null;
}

/**
 * Check if a given object implements the GuidPagedResponse interface.
 */
export function instanceOfGuidPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GuidPagedResponseFromJSON(json: any): GuidPagedResponse {
    return GuidPagedResponseFromJSONTyped(json, false);
}

export function GuidPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function GuidPagedResponseToJSON(value?: GuidPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data,
    };
}

