/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeddyItemUpdateDTO
 */
export interface TeddyItemUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof TeddyItemUpdateDTO
     */
    sku?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeddyItemUpdateDTO
     */
    price?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemUpdateDTO
     */
    fabric?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemUpdateDTO
     */
    color?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeddyItemUpdateDTO
     */
    quantity?: number | null;
}

/**
 * Check if a given object implements the TeddyItemUpdateDTO interface.
 */
export function instanceOfTeddyItemUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyItemUpdateDTOFromJSON(json: any): TeddyItemUpdateDTO {
    return TeddyItemUpdateDTOFromJSONTyped(json, false);
}

export function TeddyItemUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyItemUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sku': !exists(json, 'sku') ? undefined : json['sku'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'fabric': !exists(json, 'fabric') ? undefined : json['fabric'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function TeddyItemUpdateDTOToJSON(value?: TeddyItemUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sku': value.sku,
        'price': value.price,
        'description': value.description,
        'fabric': value.fabric,
        'color': value.color,
        'quantity': value.quantity,
    };
}

