/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeddyItemUpdateIdDTO
 */
export interface TeddyItemUpdateIdDTO {
    /**
     * 
     * @type {string}
     * @memberof TeddyItemUpdateIdDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof TeddyItemUpdateIdDTO
     */
    price?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemUpdateIdDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemUpdateIdDTO
     */
    fabric?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemUpdateIdDTO
     */
    color?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeddyItemUpdateIdDTO
     */
    quantity?: number | null;
}

/**
 * Check if a given object implements the TeddyItemUpdateIdDTO interface.
 */
export function instanceOfTeddyItemUpdateIdDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyItemUpdateIdDTOFromJSON(json: any): TeddyItemUpdateIdDTO {
    return TeddyItemUpdateIdDTOFromJSONTyped(json, false);
}

export function TeddyItemUpdateIdDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyItemUpdateIdDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'fabric': !exists(json, 'fabric') ? undefined : json['fabric'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function TeddyItemUpdateIdDTOToJSON(value?: TeddyItemUpdateIdDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'price': value.price,
        'description': value.description,
        'fabric': value.fabric,
        'color': value.color,
        'quantity': value.quantity,
    };
}

