/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeddyTemplateViewDTO
 */
export interface TeddyTemplateViewDTO {
    /**
     * 
     * @type {string}
     * @memberof TeddyTemplateViewDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TeddyTemplateViewDTO
     */
    teddyName?: string | null;
}

/**
 * Check if a given object implements the TeddyTemplateViewDTO interface.
 */
export function instanceOfTeddyTemplateViewDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyTemplateViewDTOFromJSON(json: any): TeddyTemplateViewDTO {
    return TeddyTemplateViewDTOFromJSONTyped(json, false);
}

export function TeddyTemplateViewDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyTemplateViewDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'teddyName': !exists(json, 'teddyName') ? undefined : json['teddyName'],
    };
}

export function TeddyTemplateViewDTOToJSON(value?: TeddyTemplateViewDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'teddyName': value.teddyName,
    };
}

