/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TeddyItemCategoryEnum } from './TeddyItemCategoryEnum';
import {
    TeddyItemCategoryEnumFromJSON,
    TeddyItemCategoryEnumFromJSONTyped,
    TeddyItemCategoryEnumToJSON,
} from './TeddyItemCategoryEnum';
import type { TeddyItemValability } from './TeddyItemValability';
import {
    TeddyItemValabilityFromJSON,
    TeddyItemValabilityFromJSONTyped,
    TeddyItemValabilityToJSON,
} from './TeddyItemValability';

/**
 * 
 * @export
 * @interface TeddyItemDTO
 */
export interface TeddyItemDTO {
    /**
     * 
     * @type {string}
     * @memberof TeddyItemDTO
     */
    sku?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeddyItemDTO
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemDTO
     */
    fabric?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemDTO
     */
    color?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeddyItemDTO
     */
    quantity?: number;
    /**
     * 
     * @type {TeddyItemCategoryEnum}
     * @memberof TeddyItemDTO
     */
    category?: TeddyItemCategoryEnum;
    /**
     * 
     * @type {TeddyItemValability}
     * @memberof TeddyItemDTO
     */
    valability?: TeddyItemValability;
    /**
     * 
     * @type {string}
     * @memberof TeddyItemDTO
     */
    vendorName?: string | null;
}

/**
 * Check if a given object implements the TeddyItemDTO interface.
 */
export function instanceOfTeddyItemDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyItemDTOFromJSON(json: any): TeddyItemDTO {
    return TeddyItemDTOFromJSONTyped(json, false);
}

export function TeddyItemDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyItemDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sku': !exists(json, 'sku') ? undefined : json['sku'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'fabric': !exists(json, 'fabric') ? undefined : json['fabric'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'category': !exists(json, 'category') ? undefined : TeddyItemCategoryEnumFromJSON(json['category']),
        'valability': !exists(json, 'valability') ? undefined : TeddyItemValabilityFromJSON(json['valability']),
        'vendorName': !exists(json, 'vendorName') ? undefined : json['vendorName'],
    };
}

export function TeddyItemDTOToJSON(value?: TeddyItemDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sku': value.sku,
        'name': value.name,
        'price': value.price,
        'description': value.description,
        'fabric': value.fabric,
        'color': value.color,
        'quantity': value.quantity,
        'category': TeddyItemCategoryEnumToJSON(value.category),
        'valability': TeddyItemValabilityToJSON(value.valability),
        'vendorName': value.vendorName,
    };
}

