/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TeddyBuildDTOPagedResponse } from './TeddyBuildDTOPagedResponse';
import {
    TeddyBuildDTOPagedResponseFromJSON,
    TeddyBuildDTOPagedResponseFromJSONTyped,
    TeddyBuildDTOPagedResponseToJSON,
} from './TeddyBuildDTOPagedResponse';

/**
 * 
 * @export
 * @interface TeddyBuildDTOPagedResponseRequestResponse
 */
export interface TeddyBuildDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {TeddyBuildDTOPagedResponse}
     * @memberof TeddyBuildDTOPagedResponseRequestResponse
     */
    response?: TeddyBuildDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TeddyBuildDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TeddyBuildDTOPagedResponseRequestResponse interface.
 */
export function instanceOfTeddyBuildDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyBuildDTOPagedResponseRequestResponseFromJSON(json: any): TeddyBuildDTOPagedResponseRequestResponse {
    return TeddyBuildDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function TeddyBuildDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyBuildDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : TeddyBuildDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TeddyBuildDTOPagedResponseRequestResponseToJSON(value?: TeddyBuildDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': TeddyBuildDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

