/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TeddyItemViewDTO } from './TeddyItemViewDTO';
import {
    TeddyItemViewDTOFromJSON,
    TeddyItemViewDTOFromJSONTyped,
    TeddyItemViewDTOToJSON,
} from './TeddyItemViewDTO';

/**
 * 
 * @export
 * @interface TeddyItemViewDTORequestResponse
 */
export interface TeddyItemViewDTORequestResponse {
    /**
     * 
     * @type {TeddyItemViewDTO}
     * @memberof TeddyItemViewDTORequestResponse
     */
    response?: TeddyItemViewDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TeddyItemViewDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TeddyItemViewDTORequestResponse interface.
 */
export function instanceOfTeddyItemViewDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyItemViewDTORequestResponseFromJSON(json: any): TeddyItemViewDTORequestResponse {
    return TeddyItemViewDTORequestResponseFromJSONTyped(json, false);
}

export function TeddyItemViewDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyItemViewDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : TeddyItemViewDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TeddyItemViewDTORequestResponseToJSON(value?: TeddyItemViewDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': TeddyItemViewDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

