/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TeddyFillingEnum = {
    Polyester: 'Polyester',
    Wool: 'Wool',
    Cotton: 'Cotton',
    Foam: 'Foam',
    Microbeans: 'Microbeans',
    Empty: 'Empty'
} as const;
export type TeddyFillingEnum = typeof TeddyFillingEnum[keyof typeof TeddyFillingEnum];


export function TeddyFillingEnumFromJSON(json: any): TeddyFillingEnum {
    return TeddyFillingEnumFromJSONTyped(json, false);
}

export function TeddyFillingEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyFillingEnum {
    return json as TeddyFillingEnum;
}

export function TeddyFillingEnumToJSON(value?: TeddyFillingEnum | null): any {
    return value as any;
}

