/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TeddyTemplateViewDTOPagedResponse } from './TeddyTemplateViewDTOPagedResponse';
import {
    TeddyTemplateViewDTOPagedResponseFromJSON,
    TeddyTemplateViewDTOPagedResponseFromJSONTyped,
    TeddyTemplateViewDTOPagedResponseToJSON,
} from './TeddyTemplateViewDTOPagedResponse';

/**
 * 
 * @export
 * @interface TeddyTemplateViewDTOPagedResponseRequestResponse
 */
export interface TeddyTemplateViewDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {TeddyTemplateViewDTOPagedResponse}
     * @memberof TeddyTemplateViewDTOPagedResponseRequestResponse
     */
    response?: TeddyTemplateViewDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TeddyTemplateViewDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TeddyTemplateViewDTOPagedResponseRequestResponse interface.
 */
export function instanceOfTeddyTemplateViewDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyTemplateViewDTOPagedResponseRequestResponseFromJSON(json: any): TeddyTemplateViewDTOPagedResponseRequestResponse {
    return TeddyTemplateViewDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function TeddyTemplateViewDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyTemplateViewDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : TeddyTemplateViewDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TeddyTemplateViewDTOPagedResponseRequestResponseToJSON(value?: TeddyTemplateViewDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': TeddyTemplateViewDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

