/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TeddyItemValability = {
    Available: 'Available',
    OutOfStock: 'OutOfStock',
    LowStock: 'LowStock'
} as const;
export type TeddyItemValability = typeof TeddyItemValability[keyof typeof TeddyItemValability];


export function TeddyItemValabilityFromJSON(json: any): TeddyItemValability {
    return TeddyItemValabilityFromJSONTyped(json, false);
}

export function TeddyItemValabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyItemValability {
    return json as TeddyItemValability;
}

export function TeddyItemValabilityToJSON(value?: TeddyItemValability | null): any {
    return value as any;
}

