/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeddyTemplateAddDTO
 */
export interface TeddyTemplateAddDTO {
    /**
     * 
     * @type {Blob}
     * @memberof TeddyTemplateAddDTO
     */
    file?: Blob | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyTemplateAddDTO
     */
    teddyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeddyTemplateAddDTO
     */
    filename?: string | null;
}

/**
 * Check if a given object implements the TeddyTemplateAddDTO interface.
 */
export function instanceOfTeddyTemplateAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyTemplateAddDTOFromJSON(json: any): TeddyTemplateAddDTO {
    return TeddyTemplateAddDTOFromJSONTyped(json, false);
}

export function TeddyTemplateAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyTemplateAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': !exists(json, 'file') ? undefined : json['file'],
        'teddyName': !exists(json, 'teddyName') ? undefined : json['teddyName'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
    };
}

export function TeddyTemplateAddDTOToJSON(value?: TeddyTemplateAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
        'teddyName': value.teddyName,
        'filename': value.filename,
    };
}

