/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TeddyFillingEnum } from './TeddyFillingEnum';
import {
    TeddyFillingEnumFromJSON,
    TeddyFillingEnumFromJSONTyped,
    TeddyFillingEnumToJSON,
} from './TeddyFillingEnum';

/**
 * 
 * @export
 * @interface TeddyViewDTO
 */
export interface TeddyViewDTO {
    /**
     * 
     * @type {string}
     * @memberof TeddyViewDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TeddyViewDTO
     */
    name?: string | null;
    /**
     * 
     * @type {TeddyFillingEnum}
     * @memberof TeddyViewDTO
     */
    filling?: TeddyFillingEnum;
    /**
     * 
     * @type {string}
     * @memberof TeddyViewDTO
     */
    teddyTemplateId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TeddyViewDTO
     */
    itemsIds?: Array<string> | null;
}

/**
 * Check if a given object implements the TeddyViewDTO interface.
 */
export function instanceOfTeddyViewDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeddyViewDTOFromJSON(json: any): TeddyViewDTO {
    return TeddyViewDTOFromJSONTyped(json, false);
}

export function TeddyViewDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeddyViewDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'filling': !exists(json, 'filling') ? undefined : TeddyFillingEnumFromJSON(json['filling']),
        'teddyTemplateId': !exists(json, 'teddyTemplateId') ? undefined : json['teddyTemplateId'],
        'itemsIds': !exists(json, 'itemsIds') ? undefined : json['itemsIds'],
    };
}

export function TeddyViewDTOToJSON(value?: TeddyViewDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'filling': TeddyFillingEnumToJSON(value.filling),
        'teddyTemplateId': value.teddyTemplateId,
        'itemsIds': value.itemsIds,
    };
}

