/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VendorViewDTO } from './VendorViewDTO';
import {
    VendorViewDTOFromJSON,
    VendorViewDTOFromJSONTyped,
    VendorViewDTOToJSON,
} from './VendorViewDTO';

/**
 * 
 * @export
 * @interface VendorViewDTOPagedResponse
 */
export interface VendorViewDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof VendorViewDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof VendorViewDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof VendorViewDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<VendorViewDTO>}
     * @memberof VendorViewDTOPagedResponse
     */
    data?: Array<VendorViewDTO> | null;
}

/**
 * Check if a given object implements the VendorViewDTOPagedResponse interface.
 */
export function instanceOfVendorViewDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VendorViewDTOPagedResponseFromJSON(json: any): VendorViewDTOPagedResponse {
    return VendorViewDTOPagedResponseFromJSONTyped(json, false);
}

export function VendorViewDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorViewDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(VendorViewDTOFromJSON)),
    };
}

export function VendorViewDTOPagedResponseToJSON(value?: VendorViewDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(VendorViewDTOToJSON)),
    };
}

