/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { VendorViewDTOPagedResponse } from './VendorViewDTOPagedResponse';
import {
    VendorViewDTOPagedResponseFromJSON,
    VendorViewDTOPagedResponseFromJSONTyped,
    VendorViewDTOPagedResponseToJSON,
} from './VendorViewDTOPagedResponse';

/**
 * 
 * @export
 * @interface VendorViewDTOPagedResponseRequestResponse
 */
export interface VendorViewDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {VendorViewDTOPagedResponse}
     * @memberof VendorViewDTOPagedResponseRequestResponse
     */
    response?: VendorViewDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof VendorViewDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the VendorViewDTOPagedResponseRequestResponse interface.
 */
export function instanceOfVendorViewDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VendorViewDTOPagedResponseRequestResponseFromJSON(json: any): VendorViewDTOPagedResponseRequestResponse {
    return VendorViewDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function VendorViewDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorViewDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : VendorViewDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function VendorViewDTOPagedResponseRequestResponseToJSON(value?: VendorViewDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': VendorViewDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

