/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { VendorContractDTO } from './VendorContractDTO';
import {
    VendorContractDTOFromJSON,
    VendorContractDTOFromJSONTyped,
    VendorContractDTOToJSON,
} from './VendorContractDTO';

/**
 * 
 * @export
 * @interface VendorContractDTORequestResponse
 */
export interface VendorContractDTORequestResponse {
    /**
     * 
     * @type {VendorContractDTO}
     * @memberof VendorContractDTORequestResponse
     */
    response?: VendorContractDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof VendorContractDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the VendorContractDTORequestResponse interface.
 */
export function instanceOfVendorContractDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VendorContractDTORequestResponseFromJSON(json: any): VendorContractDTORequestResponse {
    return VendorContractDTORequestResponseFromJSONTyped(json, false);
}

export function VendorContractDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorContractDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : VendorContractDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function VendorContractDTORequestResponseToJSON(value?: VendorContractDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': VendorContractDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

