/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VendorViewDTO
 */
export interface VendorViewDTO {
    /**
     * 
     * @type {string}
     * @memberof VendorViewDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof VendorViewDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorViewDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorViewDTO
     */
    address?: string | null;
}

/**
 * Check if a given object implements the VendorViewDTO interface.
 */
export function instanceOfVendorViewDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VendorViewDTOFromJSON(json: any): VendorViewDTO {
    return VendorViewDTOFromJSONTyped(json, false);
}

export function VendorViewDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorViewDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function VendorViewDTOToJSON(value?: VendorViewDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'address': value.address,
    };
}

