/* tslint:disable */
/* eslint-disable */
/**
 * Build a bear Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface VendorUserRegisterDTO
 */
export interface VendorUserRegisterDTO {
    /**
     * 
     * @type {string}
     * @memberof VendorUserRegisterDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorUserRegisterDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorUserRegisterDTO
     */
    password?: string | null;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof VendorUserRegisterDTO
     */
    role?: UserRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof VendorUserRegisterDTO
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorUserRegisterDTO
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorUserRegisterDTO
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorUserRegisterDTO
     */
    vendorEmail?: string | null;
}

/**
 * Check if a given object implements the VendorUserRegisterDTO interface.
 */
export function instanceOfVendorUserRegisterDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VendorUserRegisterDTOFromJSON(json: any): VendorUserRegisterDTO {
    return VendorUserRegisterDTOFromJSONTyped(json, false);
}

export function VendorUserRegisterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorUserRegisterDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'role': !exists(json, 'role') ? undefined : UserRoleEnumFromJSON(json['role']),
        'country': !exists(json, 'country') ? undefined : json['country'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'vendorEmail': !exists(json, 'vendorEmail') ? undefined : json['vendorEmail'],
    };
}

export function VendorUserRegisterDTOToJSON(value?: VendorUserRegisterDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'password': value.password,
        'role': UserRoleEnumToJSON(value.role),
        'country': value.country,
        'city': value.city,
        'phoneNumber': value.phoneNumber,
        'vendorEmail': value.vendorEmail,
    };
}

